# Generated by Django 5.2.7 on 2025-10-28 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=15)),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10)),
                ('tanggal_lapor', models.DateTimeField(auto_now_add=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga')),
            ],
        ),
    ]
